avi_job_category:
    resource: "@AviJobBundle/Controller/CategoryController.php"
    type:     annotation

avi_job:
    resource: "@AviJobBundle/Resources/config/routing.xml"
    prefix:   /

avi_user:
    resource: "@AviJobBundle/Resources/config/all.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
